version: '3.9'

services:
  db:
    image: postgres
    env_file:
      - .env
    container_name: nest-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    container_name: nest-pgadmin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped
    
  server:
    build:
      context: .
      dockerfile: Dockerfile
    # image: khangtgr/nestjs-server
    env_file:
      - .env
    container_name: nest-server
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nest-nginx
    ports:
      - '8080:8080'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
