version: '3.9'

services:
  db:
    image: postgres
    environment:
      PGDATA: /data/postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
    container_name: nest-postgresdb
    volumes:
      - postgres_data:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - server-network
    restart: unless-stopped

  server:
    image: khangtgr/nestjs-server
    container_name: nest-server
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    networks:
      - server-network

  nginx:
    image: nginx:latest
    container_name: nest-nginx
    ports:
      - '8080:8080'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
    networks:
      - server-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: nest-pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - db
    networks:
      - server-network
    restart: unless-stopped

networks:
  server-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
